version: "3.7"
networks:
  default:
    ipam:
      config:
      - subnet: 192.168.8.0/16
services:
    softangel-app:
        build:
            context: ./
        ports:
            - 127.0.0.1:3000:3000
        env_file:
            - .env.local
        restart:  always
